### ISSUE TITLE
Failed to prune state snapshot: not old enough yet: need 128 more blocks

### ISSUE THREAD

**Issue by ofarukcaki** [bnb-chain/bsc#1098] opened 2022-09-24 08:48 UTC
#### System information

Geth version: ` 1.1.13`
OS & Version: OSX  12.4
```./geth version
Geth
Version: 1.1.13
Architecture: arm64
Go Version: go1.19.1
Operating System: darwin
```

#### Expected behaviour
I wanted to do prune state and free up some disk space.

#### Actual behaviour
`./geth snapshot prune-state --datadir node` command is always failed with the message:
```
./geth snapshot prune-state --datadir node
INFO [09-24|11:42:54.060] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-24|11:42:54.061] Set global gas cap                       cap=50,000,000
INFO [09-24|11:42:54.061] Allocated cache and file handles         database=/Volumes/Kingston/bsc/node/geth/chaindata cache=408.00MiB handles=5120
INFO [09-24|11:42:55.105] AncientDB item count                     items=21,500,074
INFO [09-24|11:42:55.105] Opened ancient database                  database=/Volumes/Kingston/bsc/node/geth/chaindata/ancient readonly=false frozen=21,500,074
WARN [09-24|11:42:55.114] Snapshot maintenance disabled (syncing)
INFO [09-24|11:42:55.125] Initialized state bloom                  size=2.00GiB
ERROR[09-24|11:43:31.784] Failed to prune state                    err="snapshot not old enough yet: need 128 more blocks"
snapshot not old enough yet: need 128 more blocks
```

#### Steps to reproduce the behaviour
1. I ran my node with `./geth --datadir node --config config.toml --cache 12000 --maxpeers 600 --ipcpath ~/geth.ipc --txlookuplimit 300 -diffsync=true --syncmode=full --tries-verify-mode=none --diffblock=5000 --snapshot=true` for a while, at least 128 blocks.
2. Then I stopped the node and run again with `./geth --datadir node --config config.toml --cache 12000 --maxpeers 600 --ipcpath ~/geth.ipc --txlookuplimit 300 -diffsync=true --syncmode=full --tries-verify-mode=none --diffblock=5000 --snapshot=false` and leave it overnight.
3. I stopped the node and tried to prune state with the `./geth snapshot prune-state --datadir node` but it always give me the same error

**Comment by guagualvcha** [comment] 2022-09-27 05:11
hi, @ofarukcaki  it may be caused by force stop, you can restart your node and run for few hours, then stop and try again.

**Comment by guagualvcha** [comment] 2022-09-30 02:04
kindly close the issue, feel free to open new ones.

**Closed by guagualvcha** 2022-09-30 02:04 UTC
