### ISSUE TITLE
Build fails on FreeBSD 13

### ISSUE THREAD

**Issue by mcoelho80** [bnb-chain/bsc#1747] opened 2023-07-02 20:40 UTC
Geth version: 1.2.8
OS & Version: FreeBSD 13.2 
Go: go version go1.20.3 freebsd/amd64

```
# make geth
env GO111MODULE=on go run build/ci.go install ./cmd/geth
>>> /usr/local/go120/bin/go build -trimpath -v -o /usr/home/admin/setup/bsc/1.2.8/build/bin/geth ./cmd/geth
github.com/ethereum/go-ethereum/crypto/secp256k1
github.com/ethereum/go-ethereum/params
github.com/prysmaticlabs/prysm/v4/crypto/bls
# github.com/prysmaticlabs/prysm/v4/crypto/bls
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:19:14: undefined: blst.SecretKeyFromBytes
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:24:14: undefined: blst.PublicKeyFromBytes
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:29:14: undefined: blst.SignatureFromBytes
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:34:14: undefined: blst.MultipleSignaturesFromBytes
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:39:14: undefined: blst.AggregatePublicKeys
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:44:14: undefined: blst.AggregateMultiplePubkeys
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:49:14: undefined: blst.AggregateSignatures
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:54:14: undefined: blst.AggregateCompressedSignatures
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:59:14: undefined: blst.VerifySignature
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:64:14: undefined: blst.VerifyMultipleSignatures
/root/go/pkg/mod/github.com/prysmaticlabs/prysm/v4@v4.0.2/crypto/bls/bls.go:64:14: too many errors
github.com/ethereum/go-ethereum/internal/flags
github.com/prysmaticlabs/prysm/v4/config/params
github.com/prysmaticlabs/prysm/v4/io/file
github.com/prysmaticlabs/prysm/v4/cmd/validator/flags
github.com/prysmaticlabs/prysm/v4/time/slots
github.com/prysmaticlabs/prysm/v4/io/logs
github.com/prysmaticlabs/prysm/v4/cmd
github.com/prysmaticlabs/prysm/v4/config/features
github.com/prysmaticlabs/prysm/v4/beacon-chain/p2p/encoder
github.com/prysmaticlabs/prysm/v4/cmd/beacon-chain/flags
github.com/cometbft/cometbft/votepool
# github.com/cometbft/cometbft/votepool
/root/go/pkg/mod/github.com/bnb-chain/greenfield-tendermint@v0.0.0-20230417032003-4cda1f296fb2/votepool/verifier.go:89:25: undefined: blst.PublicKeyFromBytes
/root/go/pkg/mod/github.com/bnb-chain/greenfield-tendermint@v0.0.0-20230417032003-4cda1f296fb2/votepool/verifier.go:93:25: undefined: blst.SignatureFromBytes
util.go:46: exit status 1
exit status 1
*** Error code 1

Stop.
make: stopped in /usr/home/admin/setup/bsc/1.2.8
```

**Comment by CocoStarZ** [comment] 2023-07-03 01:20
Can't reproduce it on mac/linux, will further check the freebsd os internally.

**Comment by CocoStarZ** [comment] 2023-09-08 00:05
No more follow up, will close it for now.

**Closed by CocoStarZ** 2023-09-08 00:05 UTC
