### ISSUE TITLE
Questions about peers

### ISSUE THREAD

**Issue by James19903** [bnb-chain/bsc#879] opened 2022-04-27 15:16 UTC
I am trying to understand what the difference is between peers I am connected to.
Here is an example of a peer: It is a static peer that is already in the config.toml.

    caps: ["diff/1", "eth/65", "eth/66", "eth/67", "les/2", "les/3", "les/4", "snap/1"],
    enode: "enode://ace8e3b7e96290392a9c6238e005539dd1d1ca7c18aeedd979087789812e0656407e2c4baabcd83b50d583b583aa959ff42e5c95571d76b84995aad722a9a85c@44.198.55.182:30311",
    id: "25b173c00d58eac53442faee5a67f1543e496bd7df818e062cee202b8ec5582e",
    name: "Geth/v1.1.9-14512836/linux-amd64/go1.17.2",
    network: {
      inbound: false,
      localAddress: "X.X.X.X.X:45292",
      remoteAddress: "44.198.55.182:30311",
      static: true,
      trusted: false
    },
    protocols: {
      diff: {
        diff_sync: false,
        version: 1
      },
      eth: {
        difficulty: 34417574,
        head: "0x2499482b54cdaa4bdfd2f02ac8843a7ed135e3b7258585a54ce9463c374eb3b5",
        version: 67
      },
      snap: {
        version: 1
    
   
Questions:

1) What does inbound: false mean . Does this mean that the node has nodiscovery on?
2) difficulty: 34417574, | What does this represent? Is a higher number better or worse ?
3) diff_sync: false, | Is it faster to be connected to Nodes that have this as true rather than false? Does --pipecommit cause this setting to be false?
4) snap: { version: 1 | Is it better to be connected to Nodes that have this enabled? Or it doesn't matter?

**Comment by Loverush** [comment] 2022-04-28 08:22
1. inbound determines who initiates the connection, you or the node

**Comment by ktrout1111** [comment] 2022-05-02 19:44
Most "nodes" are just bots spamming arb backrun txs due to the devs merging in a change made by the Eth devs a year ago that was intended to reduce spam but actually results in more spam than ever (hundreds of txs per block coming from a single user), and all of the arb revenue going to a single entity.

These nodes aren't relaying txs or block data as an actual node would. At least when txs were ordered within a block randomly it was fair. Now it's a joke.

**Comment by James19903** [comment] 2022-05-04 00:29
> Most "nodes" are just bots spamming arb backrun txs due to the devs merging in a change made by the Eth devs a year ago that was intended to reduce spam but actually results in more spam than ever (hundreds of txs per block coming from a single user), and all of the arb revenue going to a single entity.
> 
> These nodes aren't relaying txs or block data as an actual node would. At least when txs were ordered within a block randomly it was fair. Now it's a joke.

I never knew about this, what benefit does a single entity have by spamming hundreds of tx's per block? Is there any way I can avoid these bad nodes in my network?

**Comment by ktrout1111** [comment] 2022-05-04 08:58
> I never knew about this, what benefit does a single entity have by spamming hundreds of tx's per block?

Millions and millions of dollars worth of free crypto. Arb backrunning is an extremely lucrative practice on BSC. It used to be a level playing field back when txs of equal gas price were randomly distributed. About a year ago, in an effort to combat the spam that arose from this, the Ethereum devs changed the code so that txs of equal gas price were sorted in "seen first" order. This change was silently merged into BSC way back in version 1.10, I think. 

Not all the Eth devs were on the same page about this being the best solution. It was pointed out that seen-first sortation leads to a different kind of spam. Bot operators now have to run lots and lots (hundreds) of nodes all spamming their arb txs and censoring everyone else's to give them the best chance of being first. This is what has happened on BSC, and I suspect it is a major contributing factor to the problems experienced by everyone else trying to run nodes.

I carried out an analysis a few months ago and found that most "nodes" I would connect to in a given session were not real full nodes at all. They would not respond to explicit requests for tx bodies, but were proactively sending full tx bodies of their own arb backrun txs. Crudely analysing this data it was easy to see which nodes were fake, and even which ones were being operated by who. It was how I was able to tell that the following 4 contracts are all owned by the same person/entity. Back when I did this analysis (around Feb) they were by far the biggest fish in the sea, running at least 200 "nodes" (and probably a lot more now):

https://bscscan.com/address/0xaf25d6494a341675186f975c4cbc081fdac05dbc#tokentxns
https://bscscan.com/address/0x468fc54b82b590d1698251d2bce1a9f91c43f042#tokentxns
https://bscscan.com/address/0x4834c08f5aaab44c8bdeddc386eca4029e3c6c40#tokentxns
https://bscscan.com/address/0x3948392c35fabb910d6ebe222b570fb52bf0844a#tokentxns

Between them they are spamming as many as 200 txs _**per block**_!

I'm happy to share the analysis code (it's a basic modification of eth/fetcher/txFetcher.go) if the devs are actually interested in fixing this problem. I brought it up in another thread a few months ago and heard nothing back. @Loverush, any thoughts? BSC geth is badly in need of a way to flush out these fake nodes and/or a fix to the tx sorting algorithm. The Eth devs were trying to stop tx spam by changing the tx sort to "seen first", but not only has that not worked on BSC (tx spam is greater than ever), but it has also polluted the network with spammer nodes, so it's the worst of both worlds now, and has been that way for a year.

Sorting by tx hash ought to reduce tx spam considerably and completely eliminate any need to run faux nodes.

**Comment by mariusba** [comment] 2022-05-05 22:26
> > I never knew about this, what benefit does a single entity have by spamming hundreds of tx's per block?
> 
> Millions and millions of dollars worth of free crypto. Arb backrunning is an extremely lucrative practice on BSC. It used to be a level playing field back when txs of equal gas price were randomly distributed. About a year ago, in an effort to combat the spam that arose from this, the Ethereum devs changed the code so that txs of equal gas price were sorted in "seen first" order. This change was silently merged into BSC way back in version 1.10, I think.
> 
> Not all the Eth devs were on the same page about this being the best solution. It was pointed out that seen-first sortation leads to a different kind of spam. Bot operators now have to run lots and lots (hundreds) of nodes all spamming their arb txs and censoring everyone else's to give them the best chance of being first. This is what has happened on BSC, and I suspect it is a major contributing factor to the problems experienced by everyone else trying to run nodes.
> 
> I carried out an analysis a few months ago and found that most "nodes" I would connect to in a given session were not real full nodes at all. They would not respond to explicit requests for tx bodies, but were proactively sending full tx bodies of their own arb backrun txs. Crudely analysing this data it was easy to see which nodes were fake, and even which ones were being operated by who. It was how I was able to tell that the following 4 contracts are all owned by the same person/entity. Back when I did this analysis (around Feb) they were by far the biggest fish in the sea, running at least 200 "nodes" (and probably a lot more now):
> 
> https://bscscan.com/address/0xaf25d6494a341675186f975c4cbc081fdac05dbc#tokentxns https://bscscan.com/address/0x468fc54b82b590d1698251d2bce1a9f91c43f042#tokentxns https://bscscan.com/address/0x4834c08f5aaab44c8bdeddc386eca4029e3c6c40#tokentxns https://bscscan.com/address/0x3948392c35fabb910d6ebe222b570fb52bf0844a#tokentxns
> 
> Between them they are spamming as many as 200 txs _**per block**_!
> 
> I'm happy to share the analysis code (it's a basic modification of eth/fetcher/txFetcher.go) if the devs are actually interested in fixing this problem. I brought it up in another thread a few months ago and heard nothing back. @Loverush, any thoughts? BSC geth is badly in need of a way to flush out these fake nodes and/or a fix to the tx sorting algorithm. The Eth devs were trying to stop tx spam by changing the tx sort to "seen first", but not only has that not worked on BSC (tx spam is greater than ever), but it has also polluted the network with spammer nodes, so it's the worst of both worlds now, and has been that way for a year.
> 
> Sorting by tx hash ought to reduce tx spam considerably and completely eliminate any need to run faux nodes.

hI, @ktrout1111 could you please share your analysis code? I am trying to improve my node, so that would be great to blacklist useless nodes

**Comment by James19903** [comment] 2022-05-06 12:13
> > I never knew about this, what benefit does a single entity have by spamming hundreds of tx's per block?
> 
> Millions and millions of dollars worth of free crypto. Arb backrunning is an extremely lucrative practice on BSC. It used to be a level playing field back when txs of equal gas price were randomly distributed. About a year ago, in an effort to combat the spam that arose from this, the Ethereum devs changed the code so that txs of equal gas price were sorted in "seen first" order. This change was silently merged into BSC way back in version 1.10, I think.
> 
> Not all the Eth devs were on the same page about this being the best solution. It was pointed out that seen-first sortation leads to a different kind of spam. Bot operators now have to run lots and lots (hundreds) of nodes all spamming their arb txs and censoring everyone else's to give them the best chance of being first. This is what has happened on BSC, and I suspect it is a major contributing factor to the problems experienced by everyone else trying to run nodes.
> 
> I carried out an analysis a few months ago and found that most "nodes" I would connect to in a given session were not real full nodes at all. They would not respond to explicit requests for tx bodies, but were proactively sending full tx bodies of their own arb backrun txs. Crudely analysing this data it was easy to see which nodes were fake, and even which ones were being operated by who. It was how I was able to tell that the following 4 contracts are all owned by the same person/entity. Back when I did this analysis (around Feb) they were by far the biggest fish in the sea, running at least 200 "nodes" (and probably a lot more now):
> 
> https://bscscan.com/address/0xaf25d6494a341675186f975c4cbc081fdac05dbc#tokentxns https://bscscan.com/address/0x468fc54b82b590d1698251d2bce1a9f91c43f042#tokentxns https://bscscan.com/address/0x4834c08f5aaab44c8bdeddc386eca4029e3c6c40#tokentxns https://bscscan.com/address/0x3948392c35fabb910d6ebe222b570fb52bf0844a#tokentxns
> 
> Between them they are spamming as many as 200 txs _**per block**_!
> 
> I'm happy to share the analysis code (it's a basic modification of eth/fetcher/txFetcher.go) if the devs are actually interested in fixing this problem. I brought it up in another thread a few months ago and heard nothing back. @Loverush, any thoughts? BSC geth is badly in need of a way to flush out these fake nodes and/or a fix to the tx sorting algorithm. The Eth devs were trying to stop tx spam by changing the tx sort to "seen first", but not only has that not worked on BSC (tx spam is greater than ever), but it has also polluted the network with spammer nodes, so it's the worst of both worlds now, and has been that way for a year.
> 
> Sorting by tx hash ought to reduce tx spam considerably and completely eliminate any need to run faux nodes.

This is disappointing that nothing has changed since that update.  I would like to look into this further aswell, is there a specific way to identify these nodes?

**Comment by ktrout1111** [comment] 2022-05-06 18:18
> hI, @ktrout1111 could you please share your analysis code?

It's been a while since I looked at the code, the modifications are rather extensive and messy, affecting many files. If there is enough interest in this issue (particularly from the devs), then I will write a new analyser against the latest master that fits in one file that will be easier to deploy and use. 

> This is disappointing that nothing has changed since that update. I would like to look into this further aswell, is there a specific way to identify these nodes?

It's pretty simple. Most of the action is in eth/fetcher/tx_fetcher.go and eth/handler.go. The handler listens for (amongst other things) announcements from its peers of tx hashes and tx bodies, which it then forwards to the fetcher. A normal full node listens for txs from its peers and imports them into its tx pool. If valid, these txs are spammed to all peers, but it only spams the full tx body (all of the tx data including gas price, receive address, input data, etc) to a square root of those peers, in order to conserve bandwidth. The remaining peers get only the hash.

As such, the tx fetcher receives these two forms of tx message via two different functions: Notify() for hashes, and Enqueue() for full txs. Each of these methods receive a string identifying which peer the message came from. Analysing, or simply counting how many times each of these methods is hit per peer can be very telling. Depending on the luck of the draw of which peers I get, I find that around 50-90% of them are sending no hashes at all via Notify, and what I receive from them via Enqueue is exclusively packets of 2 txs where the first is the target tx to backrun, and the second is a tx to one of their bot contracts to execute the arb. This is all they do, they are of no service to the network whatsoever, yet most users have no idea that the "peers" that they are connected to are mostly duds. Any transactions of your own that you send to these nodes get lost behind a filing cabinet.

The rabbit hole gets deeper, but I've given enough there as a starting point. I found it wasn't always black and white as to which nodes were bots or not. Different owners seem to have different philosophies as to what works best.

**Closed** 2022-05-13 08:57 UTC
Labels: question

**Comment by ktrout1111** [comment] 2022-05-13 11:41
@Loverush I take it the devs are going to continue ignoring this problem then....

**Comment by 0x090909** [comment] 2023-03-04 13:07
> > hI, @ktrout1111 could you please share your analysis code?
> 
> It's been a while since I looked at the code, the modifications are rather extensive and messy, affecting many files. If there is enough interest in this issue (particularly from the devs), then I will write a new analyser against the latest master that fits in one file that will be easier to deploy and use.
> 
> > This is disappointing that nothing has changed since that update. I would like to look into this further aswell, is there a specific way to identify these nodes?
> 
> It's pretty simple. Most of the action is in eth/fetcher/tx_fetcher.go and eth/handler.go. The handler listens for (amongst other things) announcements from its peers of tx hashes and tx bodies, which it then forwards to the fetcher. A normal full node listens for txs from its peers and imports them into its tx pool. If valid, these txs are spammed to all peers, but it only spams the full tx body (all of the tx data including gas price, receive address, input data, etc) to a square root of those peers, in order to conserve bandwidth. The remaining peers get only the hash.
> 
> As such, the tx fetcher receives these two forms of tx message via two different functions: Notify() for hashes, and Enqueue() for full txs. Each of these methods receive a string identifying which peer the message came from. Analysing, or simply counting how many times each of these methods is hit per peer can be very telling. Depending on the luck of the draw of which peers I get, I find that around 50-90% of them are sending no hashes at all via Notify, and what I receive from them via Enqueue is exclusively packets of 2 txs where the first is the target tx to backrun, and the second is a tx to one of their bot contracts to execute the arb. This is all they do, they are of no service to the network whatsoever, yet most users have no idea that the "peers" that they are connected to are mostly duds. Any transactions of your own that you send to these nodes get lost behind a filing cabinet.
> 
> The rabbit hole gets deeper, but I've given enough there as a starting point. I found it wasn't always black and white as to which nodes were bots or not. Different owners seem to have different philosophies as to what works best.

Thanks for explaining this mechanics, these are very useful tips, Im now working on external tools to filter good/bad peers.

An interesting idea would be to expose statistics for each peer directly in the admin namespace for the functions of peer management

**Comment by kugimiya530** [comment] 2023-03-04 13:32
Hi I am really interest how you ignore those bad node too

Very expect if u have any plan to share us how u ignore or modified the code. Thx!

**Comment by 0x090909** [comment] 2023-03-04 13:52
From the geth console you can drop nodes that have very low difficulty, either they are just started syncing or they are spam nodes. 

> Hi I am really interest how you ignore those bad node too
> 
> Very expect if u have any plan to share us how u ignore or modified the code. Thx!
