### ISSUE TITLE
Unable to prune state

### ISSUE THREAD

**Issue by sppet** [bnb-chain/bsc#696] opened 2022-01-01 21:29 UTC
Hello,

I am using the latest version, 1.1.7

The prune state command is not working for my node.

I was running the node with 

`/home/forge/bsc-1.1.7/build/bin/geth -config ./config.toml --datadir ./node --datadir.ancient /mnt/ancient --diffsync --http --http.port 9444 --http.api 'eth,net,web3,debug,txpool' --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --ws --ws.origins '*' --ws.api 'eth,net,web3,txpool,debug' --ws.addr 0.0.0.0 --cache 30000 --rpc.allow-unprotected-txs --txlookuplimit 50000 --syncmode snap --snapshot=true`

command and then stopped it gracefully and then ran

`/home/forge/bsc-1.1.7/build/bin/geth snapshot prune-state --datadir node/ -datadir.ancient /mnt/ancient
`
command and it gave the error below:

```
INFO [01-01|20:41:55.629] Iterating state snapshot                 accounts=28,096,282 slots=361,512,906 elapsed=8m48.017s   eta=14m21.557s
INFO [01-01|20:42:03.629] Iterating state snapshot                 accounts=28,519,681 slots=365,106,261 elapsed=8m56.017s   eta=14m13.693s
ERROR[01-01|20:42:03.975] Failed to prune state                    err="invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2"
invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2
```

In the latest release notes, this issue is mentioned but it was not related to the pruning state. I am only getting this error when running the prune command. 

As the release note suggests, I started the node with

`/home/forge/bsc-1.1.7/build/bin/geth -config ./config.toml --datadir ./node --datadir.ancient /mnt/ancient --diffsync --http --http.port 9444 --http.api 'eth,net,web3,debug,txpool' --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --ws --ws.origins '*' --ws.api 'eth,net,web3,txpool,debug' --ws.addr 0.0.0.0 --cache 30000 --rpc.allow-unprotected-txs --txlookuplimit 50000 --syncmode snap --snapshot=false
`
command and waited 30 minutes and stopped the node gracefully, the output was like this:

```
t=2022-01-01T21:15:02+0000 lvl=warn msg="Failed to decode block body"            block=16 error=EOF
t=2022-01-01T21:15:02+0000 lvl=info msg="Unindexed transactions"                 blocks=0   txs=0    tail=13,945,129 elapsed="614.153µs"
t=2022-01-01T21:15:04+0000 lvl=info msg="Got interrupt, shutting down..."
t=2022-01-01T21:15:04+0000 lvl=info msg="HTTP server stopped"                    endpoint=127.0.0.1:9444
t=2022-01-01T21:15:04+0000 lvl=info msg="HTTP server stopped"                    endpoint=[::]:8546
t=2022-01-01T21:15:04+0000 lvl=info msg="IPC endpoint closed"                    url=/home/forge/node/geth.ipc
t=2022-01-01T21:15:04+0000 lvl=info msg="Ethereum protocol stopped"
t=2022-01-01T21:15:04+0000 lvl=info msg="Transaction pool stopped"
t=2022-01-01T21:15:09+0000 lvl=info msg="Writing cached state to disk"           block=13,995,128 hash=0x0d1ec9b69e2f2064ff12a078078d8cff94612ee27d81c8b987fce5c38fc13263 root=0x50ac30d841c2d0f23d4cc352b907abf7143454130d744bbde7dbb32b47508c3e
t=2022-01-01T21:15:14+0000 lvl=info msg="Looking for peers"                      peercount=0 tried=202 static=25
t=2022-01-01T21:15:15+0000 lvl=eror msg="Snapshot extension registration failed" peer=635d0ba6 err="peer connected on snap without compatible eth support"
t=2022-01-01T21:15:18+0000 lvl=info msg="Persisted trie from memory database"    nodes=1,262,571 size="361.81 MiB" time=8.38048824s  gcnodes=2,261,836 gcsize="872.59 MiB" gctime=7.465844598s livenodes=639,088 livesize="242.91 MiB"
t=2022-01-01T21:15:18+0000 lvl=info msg="Writing cached state to disk"           block=13,995,127 hash=0x5d75786c15eb0b2b99ea667b397b07c64d6a46cc282c3b3925b35a3783aa7ee0 root=0x74355d12622857cc0b7ca4d1865ea19ed563884da91cb66b3e6f638d55d81460
t=2022-01-01T21:15:18+0000 lvl=info msg="Persisted trie from memory database"    nodes=6620      size="2.55 MiB"   time=61.694306ms  gcnodes=0         gcsize="0.00 B"     gctime=0s           livenodes=632,468 livesize="240.36 MiB"
t=2022-01-01T21:15:18+0000 lvl=info msg="Writing cached state to disk"           block=13,995,001 hash=0xd34459bf464a5e5cb23d1bcbf1c55143fab3de6d865432f18de1447bb7082023 root=0x91b24bafbdab8abfd798df4f3806c81fee6e4ff25b09ffcf3060b2230cd166ec
t=2022-01-01T21:15:19+0000 lvl=info msg="Persisted trie from memory database"    nodes=153,756   size="56.92 MiB"  time=1.213675965s gcnodes=0         gcsize="0.00 B"     gctime=0s           livenodes=478,712 livesize="183.43 MiB"
t=2022-01-01T21:15:19+0000 lvl=info msg="Writing snapshot state to disk"         root=0x0a75790dfb45b45ca8b1605e59308652ecc42d2d13db7893a64ad5d86f37df9d
t=2022-01-01T21:15:19+0000 lvl=info msg="Persisted trie from memory database"    nodes=0         size="0.00 B"     time="2.134µs"    gcnodes=0         gcsize="0.00 B"     gctime=0s           livenodes=478,712 livesize="183.43 MiB"
t=2022-01-01T21:15:19+0000 lvl=eror msg="Dangling trie nodes after full cleanup"
t=2022-01-01T21:15:19+0000 lvl=info msg="Writing clean trie cache to disk"       path=/home/forge/node/geth/triecache threads=16
t=2022-01-01T21:15:19+0000 lvl=info msg="Persisted the clean trie cache"         path=/home/forge/node/geth/triecache elapsed=158.261ms
t=2022-01-01T21:15:19+0000 lvl=info msg="Blockchain stopped"
```

Then i ran the prune command with 
`/home/forge/bsc-1.1.7/build/bin/geth snapshot prune-state --datadir node/ -datadir.ancient /mnt/ancient
`

But I got the same error again

```
INFO [01-01|21:25:48.556] Iterating state snapshot                 accounts=27,521,059 slots=352,577,088 elapsed=8m16.006s  eta=13m56.664s
INFO [01-01|21:25:56.556] Iterating state snapshot                 accounts=28,028,953 slots=357,791,084 elapsed=8m24.006s  eta=13m45.614s
INFO [01-01|21:26:04.556] Iterating state snapshot                 accounts=28,362,443 slots=363,777,008 elapsed=8m32.006s  eta=13m42.856s
ERROR[01-01|21:26:07.738] Failed to prune state                    err="invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2"
invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2
```

Is there any way to recover from this error or do I need to start syncing from scratch?

Thanks in advance

**Comment by RumeelHussainbnb** [comment] 2022-01-04 10:46
This is caused by corrupted data, you may fix by these steps:
```
1.Stop bsc service and then run it with extra flag "--snapshot=false" for a while,
2.Stop bsc service and then run it without flag "--snapshot=false" for a while,
3.Stop bsc service and do prune again.
```
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by sppet** [comment] 2022-01-04 19:35
Hello,

I applied the steps you gave, but I got the same error;

`ERROR[01-04|19:14:37.003] Failed to prune state                    err="invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2"
invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2`

I also joined the Discord channel. The node-support channel looks dead. Only people looking for help seem to be posting there. I think Binance should spare some money for support from the billions they earn so we can get some rest while running the node. It has been so much trouble to run this node.

Any advice?

**Comment by RumeelHussainbnb** [comment] 2022-01-05 10:53
Afer you ran with snapshot=false, you should restart geth with snapshot=true, and then you can try to prune-state.

**Comment by sppet** [comment] 2022-01-05 11:51
Hello,


I was running for many hours with

`/home/forge/bsc-1.1.7/build/bin/geth -config ./config.toml --datadir ./node --datadir.ancient /mnt/ancient --diffsync --http --http.port 9444 --http.api 'eth,net,web3,debug,txpool' --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --ws --ws.origins '*' --ws.api 'eth,net,web3,txpool,debug' --ws.addr 0.0.0.0 --cache 30000 --rpc.allow-unprotected-txs --txlookuplimit 50000 --syncmode snap --snapshot=true`

command and gracefully stopped.

then ran with 

`/home/forge/bsc-1.1.7/build/bin/geth -config ./config.toml --datadir ./node --datadir.ancient /mnt/ancient --diffsync --http --http.port 9444 --http.api 'eth,net,web3,debug,txpool' --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --ws --ws.origins '*' --ws.api 'eth,net,web3,txpool,debug' --ws.addr 0.0.0.0 --cache 30000 --rpc.allow-unprotected-txs --txlookuplimit 50000 --syncmode snap --snapshot=false`

command for 15 minutes and gracefully stopped

then ran again with 

`/home/forge/bsc-1.1.7/build/bin/geth -config ./config.toml --datadir ./node --datadir.ancient /mnt/ancient --diffsync --http --http.port 9444 --http.api 'eth,net,web3,debug,txpool' --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --ws --ws.origins '*' --ws.api 'eth,net,web3,txpool,debug' --ws.addr 0.0.0.0 --cache 30000 --rpc.allow-unprotected-txs --txlookuplimit 50000 --syncmode snap --snapshot=true`

command for 15 minutes and gracefully stopped

then tried to prune with 

`/home/forge/bsc-1.1.7/build/bin/geth snapshot prune-state --datadir node/ -datadir.ancient /mnt/ancient
`
and got the same error:


```
INFO [01-05|11:47:38.466] Iterating state snapshot                 accounts=28,146,694 slots=367,407,779 elapsed=8m56.018s   eta=14m36.978s
INFO [01-05|11:47:46.466] Iterating state snapshot                 accounts=28,612,072 slots=371,042,449 elapsed=9m4.018s    eta=14m26.772s
ERROR[01-05|11:47:48.047] Failed to prune state                    err="invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2"
invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2
```


Here is config.toml if needed

```
[Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 100000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 40
NoDiscovery = false
BootstrapNodes = ["enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311","enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311","enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@35.73.137.11:30311"]
StaticNodes = ["enode://f3cfd69f2808ef64838abd8786342c0b22fdd28268703c8d6812e26e109f9a7cb2b37bd49724ebb46c233289f22da82991c87345eb9a2dadeddb8f37eeb259ac@18.180.28.21:30311","enode://ae74385270d4afeb953561603fcedc4a0e755a241ffdea31c3f751dc8be5bf29c03bf46e3051d1c8d997c45479a92632020c9a84b96dcb63b2259ec09b4fde38@54.178.30.104:30311","enode://d1cabe083d5fc1da9b510889188f06dab891935294e4569df759fc2c4d684b3b4982051b84a9a078512202ad947f9240adc5b6abea5320fb9a736d2f6751c52e@54.238.28.14:30311","enode://f420209bac5324326c116d38d83edfa2256c4101a27cd3e7f9b8287dc8526900f4137e915df6806986b28bc79b1e66679b544a1c515a95ede86f4d809bd65dab@54.178.62.117:30311","enode://c0e8d1abd27c3c13ca879e16f34c12ffee936a7e5d7b7fb6f1af5cc75c6fad704e5667c7bbf7826fcb200d22b9bf86395271b0f76c21e63ad9a388ed548d4c90@54.65.247.12:30311","enode://f1b49b1cf536e36f9a56730f7a0ece899e5efb344eec2fdca3a335465bc4f619b98121f4a5032a1218fa8b69a5488d1ec48afe2abda073280beec296b104db31@13.114.199.41:30311","enode://4924583cfb262b6e333969c86eab8da009b3f7d165cc9ad326914f576c575741e71dc6e64a830e833c25e8c45b906364e58e70cdf043651fd583082ea7db5e3b@18.180.17.171:30311","enode://4d041250eb4f05ab55af184a01aed1a71d241a94a03a5b86f4e32659e1ab1e144be919890682d4afb5e7afd837146ce584d61a38837553d95a7de1f28ea4513a@54.178.99.222:30311","enode://b5772a14fdaeebf4c1924e73c923bdf11c35240a6da7b9e5ec0e6cbb95e78327690b90e8ab0ea5270debc8834454b98eca34cc2a19817f5972498648a6959a3a@54.170.158.102:30311","enode://f329176b187cec87b327f82e78b6ece3102a0f7c89b92a5312e1674062c6e89f785f55fb1b167e369d71c66b0548994c6035c6d85849eccb434d4d9e0c489cdd@34.253.94.130:30311","enode://cbfd1219940d4e312ad94108e7fa3bc34c4c22081d6f334a2e7b36bb28928b56879924cf0353ad85fa5b2f3d5033bbe8ad5371feae9c2088214184be301ed658@54.75.11.3:30311","enode://c64b0a0c619c03c220ea0d7cac754931f967665f9e148b92d2e46761ad9180f5eb5aaef48dfc230d8db8f8c16d2265a3d5407b06bedcd5f0f5a22c2f51c2e69f@54.216.208.163:30311","enode://352a361a9240d4d23bb6fab19cc6dc5a5fc6921abf19de65afe13f1802780aecd67c8c09d8c89043ff86947f171d98ab06906ef616d58e718067e02abea0dda9@79.125.105.65:30311","enode://bb683ef5d03db7d945d6f84b88e5b98920b70aecc22abed8c00d6db621f784e4280e5813d12694c7a091543064456ad9789980766f3f1feb38906cf7255c33d6@54.195.127.237:30311","enode://11dc6fea50630b68a9289055d6b0fb0e22fb5048a3f4e4efd741a7ab09dd79e78d383efc052089e516f0a0f3eacdd5d3ffbe5279b36ecc42ad7cd1f2767fdbdb@46.137.182.25:30311","enode://21530e423b42aed17d7eef67882ebb23357db4f8b10c94d4c71191f52955d97dc13eec03cfeff0fe3a1c89c955e81a6970c09689d21ecbec2142b26b7e759c45@54.216.119.18:30311","enode://d61a31410c365e7fcd50e24d56a77d2d9741d4a57b295cc5070189ad90d0ec749d113b4b0432c6d795eb36597efce88d12ca45e645ec51b3a2144e1c1c41b66a@34.204.129.242:30311","enode://bb91215b1d77c892897048dd58f709f02aacb5355aa8f50f00b67c879c3dffd7eef5b5a152ac46cdfb255295bec4d06701a8032456703c6b604a4686d388ea8f@75.101.197.198:30311","enode://786acbdf5a3cf91b99047a0fd8305e11e54d96ea3a72b1527050d3d6f8c9fc0278ff9ef56f3e56b3b70a283d97c309065506ea2fc3eb9b62477fd014a3ec1a96@107.23.90.162:30311","enode://4653bc7c235c3480968e5e81d91123bc67626f35c207ae4acab89347db675a627784c5982431300c02f547a7d33558718f7795e848d547a327abb111eac73636@54.144.170.236:30311","enode://c6ffd994c4ef130f90f8ee2fc08c1b0f02a6e9b12152092bf5a03dd7af9fd33597d4b2e2000a271cc0648d5e55242aeadd6d5061bb2e596372655ba0722cc704@54.147.151.108:30311","enode://99b07e9dc5f204263b87243146743399b2bd60c98f68d1239a3461d09087e6c417e40f1106fa606ccf54159feabdddb4e7f367559b349a6511e66e525de4906e@54.81.225.170:30311","enode://1479af5ea7bda822e8747d0b967309bced22cad5083b93bc6f4e1d7da7be067cd8495dc4c5a71579f2da8d9068f0c43ad6933d2b335a545b4ae49a846122b261@52.7.247.132:30311","enode://43562d35f274d9e93f5ccac484c7cb185eabc746dbc9f3a56c36dc5a9ef05a3282695de7694a71c0bf4600651f49395b2ee7a6aaef857db2ac896e0fcbe6b518@35.73.15.198:30311","enode://08867e57849456fc9b0b00771f53e87ca6f2dd618c23b34a35d0c851cd484a4b7137905c5b357795025b368e4f8fe4c841b752b0c28cc2dbbf41a03d048e0e24@35.74.39.234:30311"]
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
```


Besides this pruning issue, the node is in sync and works fine, but I am low on space. I am running the steps wrong, or app is not behaving like it is supposed to? Let me know if you need more debug data.

**Comment by RumeelHussainbnb** [comment] 2022-01-05 14:22
Please make sure you meet the Hardware requirements. 

https://docs.binance.org/smart-chain/validator/guideline.html
https://docs.binance.org/faq/bsc/val.html#what-are-hardware-requirements-of-running-a-validator-node

**Comment by sppet** [comment] 2022-01-05 15:30
I don't think it is related to Hardware requirements, but my server meets the requirements. As I said, it is working fine and in sync. The only problem is I can not prune. Feel free not to comment if you do not know what the problem is.

Anyone has experienced and fixed this issue? Do I need to make a fresh sync? Or will there be a new release to fix this problem? Really weird Binance abandoned this place

**Comment by RumeelHussainbnb** [comment] 2022-01-05 16:50
Dude the solution i mentioned above its working with others here is the reference, for your issue let me check again. https://github.com/binance-chain/bsc/issues/623

**Comment by sppet** [comment] 2022-01-05 17:15
Yes, I just saw it. Thanks for pointing. 

Someone said to wait `until the block height is 128 higher than where it stopped`. Do you know where to view the block height in the log? For example in the below log:

```t=2022-01-05T17:14:37+0000 lvl=info msg="Unindexed transactions"                 blocks=0   txs=0     tail=14,055,278 elapsed="503.375µs"
t=2022-01-05T17:14:40+0000 lvl=eror msg="do light process err at block"          num=14,105,278 err="account storage root mismatch"
t=2022-01-05T17:14:40+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=267   mgas=35.843   elapsed=200.185ms   mgasps=179.050  number=14,105,278 hash=0xe2bb9305e1c497ca8845353ebd7814902f735d8ef0c50fbb958dc944fd799b44 dirty="923.23 MiB"
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=1  error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=2  error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=3  error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=4  error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=5  error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=6  error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=7  error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=8  error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=9  error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=10 error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=11 error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=12 error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=13 error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=14 error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=15 error=EOF
t=2022-01-05T17:14:40+0000 lvl=warn msg="Failed to decode block body"            block=16 error=EOF
t=2022-01-05T17:14:40+0000 lvl=info msg="Unindexed transactions"                 blocks=0   txs=0     tail=14,055,279 elapsed="569.921µs"
t=2022-01-05T17:14:43+0000 lvl=eror msg="do light process err at block"          num=14,105,279 err="account storage root mismatch"
t=2022-01-05T17:14:43+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=244   mgas=33.209   elapsed=244.302ms   mgasps=135.936  number=14,105,279 hash=0xda54f8cb2fda68ad7d4cf06fae3f924f326bca5a9bc03f7f17c378a0cb9f807e dirty="922.21 MiB"```

**Comment by kyrie-yl** [comment] 2022-01-14 02:03
> 

`number=xxx` indicates the block height in the log

**Comment by guagualvcha** [comment] 2022-01-14 05:54
hi @sppet  sorry for your trouble. It is an bug introduced by diffsync, it is fixed in release v1.1.7. 

You can follow the guide here to fix this issue: https://github.com/binance-chain/bsc/releases/tag/v1.1.7

1. Stop The node.
2. Upgrade the binary to the [latest release](https://github.com/binance-chain/bsc/releases/edit/v1.1.7).
3. Start the node with `--snapshot=false`
4. Wait for a few minutes(it depends on how fast the node is), until the block height is 128 higher than where it stopped.
5. Restart the node with `--snapshot=true`
6. The node will continue to sync and repair the corrupt data.

**Comment by sppet** [comment] 2022-01-14 06:03
Hello, 

I am using 1.1.7 since it is released and tried your suggestion at least 20 times but never worked. It doesn't repair for me and keeps giving the same error. However, node works well but I don't have any space left out of 3tb disk. I must start from scratch I guess.

I read on some topics that if we don't use snapshot, we won't need to prune at all? How does it work? Pruning causes the node shutdown and my clients are missing transactions which is creating problems. Also is it possible to run two geth instance with different chain folder? Will that work?

Thanks for help

**Comment by sppet** [comment] 2022-01-14 18:40
@guagualvcha can you tell me why you labeled this as a question? This is a bug of the bsc. Do not be afraid, everyone should see how pathetic and abandoned this project is

**Comment by an0nym0us101** [comment] 2022-01-18 05:30
I am noticing the same behaviour. Have already tried the usual fix of snapshot=false, wait for 128+ blocks, then snapshot=true, wait again  for 128+ blocks and then prune, but this does not help.

I am on the latest release as well v1.1.7.

Logs,
Failed to prune state                    err="invalid subroot(path 4f737fc14b6380309706168214090b29c680b5bb854714e26dc65ac55cf03673), want 59ea6d97ea7fe2bef49d6ec28fb231756061d3162608e062fe721802e6eb1062, have 764dc14a1741737673f97107e9506747391fee647d504173344a88bb2306f9d8"

**Closed** 2022-03-24 07:54 UTC
Labels: question

**Comment by sppet** [comment] 2022-03-24 17:40
Lol, closed this? Any explanation for that? Or just trying to hide the bugs under the carpet?
