### ISSUE TITLE
########## BAD BLOCK #########

### ISSUE THREAD

**Issue by perwpqwe** [bnb-chain/bsc#2355] opened 2024-03-31 14:02 UTC
#### System information

Geth version: 
Version: 1.4.3
Git Commit: 7f3f72ed410ab4a2ec08951f40037ecc035420d0
Git Commit Date: 20240321
Architecture: amd64
Go Version: go1.21.6
Operating System: linux

start command:
geth --cache 32000 --config /root/config.toml --history.transactions=0 --syncmode=full --db.engine=pebble --state.scheme=path

t=2024-03-31T21:29:54+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=4ecf8f0d90544cd47fa2ffd8c1fd9a100dbb8a41abadcdfc5d6197a746ab57b0 err="retrieved hash chain is invalid: invalid merkle root (remote: 133db3a4df5de250a9e2a7feff9102b9981d1e3e1c1622d9d20e31833058e92b local: d7a36eeb8423c8294238f2e86772257efa4d3baba570df6a2663466fea87f780) dberr: updateStateObject (e452bb71a31d220efbac44b48970e14136e4ca39) error: missing trie node 279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173 (path 0d0c0e0701) unexpected node, loc: disk, node: (0000000000000000000000000000000000000000000000000000000000000000 [13 12 14 7 1]), 279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173!=0000000000000000000000000000000000000000000000000000000000000000, blob: nil"
t=2024-03-31T21:29:55+0800 lvl=error msg="Unexpected trie node in disk" owner=0x0000000000000000000000000000000000000000000000000000000000000000 path="\r\f\x0e\a\x01" expect=0x279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173 got=0x0000000000000000000000000000000000000000000000000000000000000000
t=2024-03-31T21:29:55+0800 lvl=error msg="Unexpected trie node in disk" owner=0x0000000000000000000000000000000000000000000000000000000000000000 path="\r\f\x0e\a\x01" expect=0x279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173 got=0x0000000000000000000000000000000000000000000000000000000000000000
t=2024-03-31T21:29:55+0800 lvl=error msg="Unexpected trie node in disk" owner=0x0000000000000000000000000000000000000000000000000000000000000000 path="\r\f\x0e\a\x01" expect=0x279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173 got=0x0000000000000000000000000000000000000000000000000000000000000000
t=2024-03-31T21:29:55+0800 lvl=error msg="validate state failed" error="invalid merkle root (remote: 133db3a4df5de250a9e2a7feff9102b9981d1e3e1c1622d9d20e31833058e92b local: d7a36eeb8423c8294238f2e86772257efa4d3baba570df6a2663466fea87f780) dberr: updateStateObject (e452bb71a31d220efbac44b48970e14136e4ca39) error: missing trie node 279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173 (path 0d0c0e0701) unexpected node, loc: disk, node: (0000000000000000000000000000000000000000000000000000000000000000 [13 12 14 7 1]), 279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173!=0000000000000000000000000000000000000000000000000000000000000000, blob: nil"
t=2024-03-31T21:29:55+0800 lvl=info msg="Skip duplicated bad block" number=37438001 hash=0x2185f3e62ed8999951ffe2d6fdae7081300b8112784d59eb4b81b1186a58011a
t=2024-03-31T21:29:55+0800 lvl=error msg="\n########## BAD BLOCK #########\nBlock: 37438001 (0x2185f3e62ed8999951ffe2d6fdae7081300b8112784d59eb4b81b1186a58011a)\nMiner: 0xEF0274E31810C9Df02F98FAFDe0f841F4E66a1Cd\nError: invalid merkle root (remote: 133db3a4df5de250a9e2a7feff9102b9981d1e3e1c1622d9d20e31833058e92b local: d7a36eeb8423c8294238f2e86772257efa4d3baba570df6a2663466fea87f780) dberr: updateStateObject (e452bb71a31d220efbac44b48970e14136e4ca39) error: missing trie node 279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173 (path 0d0c0e0701) unexpected node, loc: disk, node: (0000000000000000000000000000000000000000000000000000000000000000 [13 12 14 7 1]), 279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173!=0000000000000000000000000000000000000000000000000000000000000000, blob: nil\nPlatform: geth (devel) go1.21.6 amd64 linux\nVCS: 7f3f72ed-20240321\nChain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc000155e58), KeplerTime:(*uint64)(0xc000155e60), FeynmanTime:(*uint64)(nil), FeynmanFixTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0, NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, PlanckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x4658ee0)}\nReceipts: \n  0: 
...
109: cumulative: 11452570 gas: 51008 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x057b57c6fc4d3ecfccdbe92c00f220fada75d54d7e06ae24c8db416bd1f70bc4 logs: [0xc0b3b7c160 0xc0b3b7c210 0xc0b3b7c2c0 0xc0b3b7c370] bloom: 00000000000000000000004000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002010000000000000000000000000000000080020000200000000020000000000080000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000020000000000000002008000000020000000000000000000002000000000000000000000000000000000000000000000000020000000000000000104002000000000000000000000000010000040000010000008000000000004000000000000000 state: \n##############################\n"
t=2024-03-31T21:29:55+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=1d8dca5134b6e295d25f0729facb624f153143b55b648f93218fc4f5b27e44fc err="retrieved hash chain is invalid: invalid merkle root (remote: 133db3a4df5de250a9e2a7feff9102b9981d1e3e1c1622d9d20e31833058e92b local: d7a36eeb8423c8294238f2e86772257efa4d3baba570df6a2663466fea87f780) dberr: updateStateObject (e452bb71a31d220efbac44b48970e14136e4ca39) error: missing trie node 279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173 (path 0d0c0e0701) unexpected node, loc: disk, node: (0000000000000000000000000000000000000000000000000000000000000000 [13 12 14 7 1]), 279c481c442488e086dc15924707aa81c656347a19958dfdd04703355e688173!=0000000000000000000000000000000000000000000000000000000000000000, blob: nil"
t=2024-03-31T21:30:21+0800 lvl=error msg="Bsc extension Handshake failed" peer=31975b70 err=EOF

**Comment by dandavid3000** [comment] 2024-03-31 18:18
I'm having a lot of error messages from BSC node.
```

ERROR[03-31|20:00:24.610] 
########## BAD BLOCK #########
Block: 37456780 (0xcf7fc866919867ed51db08ea4fa926c4072db028d8749386e62713ce4260bc29)
Miner: 0x61Dd481A114A2E761c554B641742C973867899D3
Error: withdrawals present in block body
Platform: geth (devel) go1.21.7 amd64 linux
VCS: c8cc9196-20240304 (dirty)
Chain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc0005947a8), KeplerTime:(*uint64)(0xc0005947b0), FeynmanTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0, NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, PlanckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x4809f70), IsDevMode:false}
Receipts: 
##############################

...

ERROR[03-31|20:15:51.517] Bsc extension Handshake failed           peer=62264006 err=EOF
INFO [03-31|20:15:54.211] Imported new chain segment               number=37,457,090 hash=fc54f4..4dadb5 miner=0xEF0274E31810C9Df02F98FAFDe0f841F4E66a1Cd blocks=1   txs=101   mgas=9.273    elapsed=39.540ms  mgasps=234.530 triedirty=0.00B
INFO [03-31|20:15:57.398] Imported new chain segment               number=37,457,091 hash=04f9eb..9b97b5 miner=0x2465176C461AfB316ebc773C61fAEe85A6515DAA blocks=1   txs=133   mgas=14.154   elapsed=122.315ms mgasps=115.715 triedirty=0.00B
INFO [03-31|20:15:58.571] Deep froze chain segment                 blocks=20  elapsed=3.184ms   number=37,367,091 hash=7a9291..8cf010
INFO [03-31|20:16:00.295] Imported new chain segment               number=37,457,092 hash=afbba1..fc2176 miner=0x295e26495CEF6F69dFA69911d9D8e4F3bBadB89B blocks=1   txs=129   mgas=13.659   elapsed=43.434ms  mgasps=314.466 triedirty=0.00B
INFO [03-31|20:16:03.166] Imported new chain segment               number=37,457,093 hash=26328e..828059 miner=0x2D4C407BBe49438ED859fe965b140dcF1aaB71a9 blocks=1   txs=148   mgas=10.664   elapsed=34.090ms  mgasps=312.803 triedirty=0.00B
ERROR[03-31|20:16:04.326] Bsc extension Handshake failed           peer=e0882aba err=EOF
ERROR[03-31|20:16:04.853] Bsc extension Handshake failed           peer=e26ee82c err=EOF
INFO [03-31|20:16:06.331] Imported new chain segment               number=37,457,094 hash=a84eb2..40bb37 miner=0x3f349bBaFEc1551819B8be1EfEA2fC46cA749aA1 blocks=1   txs=132   mgas=13.113   elapsed=46.508ms  mgasps=281.943 triedirty=0.00B
INFO [03-31|20:16:09.207] Imported new chain segment               number=37,457,095 hash=1a7944..3a44fc miner=0x61Dd481A114A2E761c554B641742C973867899D3 blocks=1   txs=151   mgas=10.347   elapsed=29.490ms  mgasps=350.862 triedirty=0.00B
INFO [03-31|20:16:12.132] Imported new chain segment               number=37,457,096 hash=3941a7..996463 miner=0x685B1ded8013785d6623CC18D214320b6Bb64759 blocks=1   txs=120   mgas=11.587   elapsed=32.808ms  mgasps=353.178 triedirty=0.00B
ERROR[03-31|20:16:12.137] Propagated block verification failed     peer=2cfc341535c576a3f92cd18148c4033ae18f85d70f01a8e7d5aea31f0fc8f09e number=37,457,096 hash=a01b22..ea3ec7 err="coinbase do not match with signature"

```

**Comment by zzzckck** [comment] 2024-04-01 03:13
> I'm having a lot of error messages from BSC node.
> 
> ```
> 
> ERROR[03-31|20:00:24.610] 
> ########## BAD BLOCK #########
> Block: 37456780 (0xcf7fc866919867ed51db08ea4fa926c4072db028d8749386e62713ce4260bc29)
> Miner: 0x61Dd481A114A2E761c554B641742C973867899D3
> Error: withdrawals present in block body
> Platform: geth (devel) go1.21.7 amd64 linux
> VCS: c8cc9196-20240304 (dirty)
> Chain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc0005947a8), KeplerTime:(*uint64)(0xc0005947b0), FeynmanTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0, NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, PlanckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x4809f70), IsDevMode:false}
> Receipts: 
> ##############################
> 
> ...
> 
> ERROR[03-31|20:15:51.517] Bsc extension Handshake failed           peer=62264006 err=EOF
> INFO [03-31|20:15:54.211] Imported new chain segment               number=37,457,090 hash=fc54f4..4dadb5 miner=0xEF0274E31810C9Df02F98FAFDe0f841F4E66a1Cd blocks=1   txs=101   mgas=9.273    elapsed=39.540ms  mgasps=234.530 triedirty=0.00B
> INFO [03-31|20:15:57.398] Imported new chain segment               number=37,457,091 hash=04f9eb..9b97b5 miner=0x2465176C461AfB316ebc773C61fAEe85A6515DAA blocks=1   txs=133   mgas=14.154   elapsed=122.315ms mgasps=115.715 triedirty=0.00B
> INFO [03-31|20:15:58.571] Deep froze chain segment                 blocks=20  elapsed=3.184ms   number=37,367,091 hash=7a9291..8cf010
> INFO [03-31|20:16:00.295] Imported new chain segment               number=37,457,092 hash=afbba1..fc2176 miner=0x295e26495CEF6F69dFA69911d9D8e4F3bBadB89B blocks=1   txs=129   mgas=13.659   elapsed=43.434ms  mgasps=314.466 triedirty=0.00B
> INFO [03-31|20:16:03.166] Imported new chain segment               number=37,457,093 hash=26328e..828059 miner=0x2D4C407BBe49438ED859fe965b140dcF1aaB71a9 blocks=1   txs=148   mgas=10.664   elapsed=34.090ms  mgasps=312.803 triedirty=0.00B
> ERROR[03-31|20:16:04.326] Bsc extension Handshake failed           peer=e0882aba err=EOF
> ERROR[03-31|20:16:04.853] Bsc extension Handshake failed           peer=e26ee82c err=EOF
> INFO [03-31|20:16:06.331] Imported new chain segment               number=37,457,094 hash=a84eb2..40bb37 miner=0x3f349bBaFEc1551819B8be1EfEA2fC46cA749aA1 blocks=1   txs=132   mgas=13.113   elapsed=46.508ms  mgasps=281.943 triedirty=0.00B
> INFO [03-31|20:16:09.207] Imported new chain segment               number=37,457,095 hash=1a7944..3a44fc miner=0x61Dd481A114A2E761c554B641742C973867899D3 blocks=1   txs=151   mgas=10.347   elapsed=29.490ms  mgasps=350.862 triedirty=0.00B
> INFO [03-31|20:16:12.132] Imported new chain segment               number=37,457,096 hash=3941a7..996463 miner=0x685B1ded8013785d6623CC18D214320b6Bb64759 blocks=1   txs=120   mgas=11.587   elapsed=32.808ms  mgasps=353.178 triedirty=0.00B
> ERROR[03-31|20:16:12.137] Propagated block verification failed     peer=2cfc341535c576a3f92cd18148c4033ae18f85d70f01a8e7d5aea31f0fc8f09e number=37,457,096 hash=a01b22..ea3ec7 err="coinbase do not match with signature"
> ```

seems like your case is about: `withdrawals present in block body`, could be same as issue: https://github.com/bnb-chain/bsc/issues/2353

**Comment by zzzckck** [comment] 2024-04-08 02:19
same issue as https://github.com/bnb-chain/bsc/issues/2364, it is likely caused by Erigon node, which broadcast bad blocks.
close this one, will update in issue#2364

**Closed by zzzckck** 2024-04-08 02:19 UTC
