### ISSUE TITLE
Could not open database:  diffs.ridx

### ISSUE THREAD

**Issue by TehnobitSystems** [bnb-chain/bsc#2018] opened 2023-11-29 22:01 UTC
Geth version: 1.3.2
OS: Ubuntu 22.04

After update Geth version to 1.3.2 I have error: 
`Could not open database: open /pathToAncient/diffs.ridx`

How to fix it?

**Comment by maoueh** [comment] 2023-11-30 01:12
Most probably duplicate of https://github.com/bnb-chain/bsc/issues/1997

**Closed** 2023-11-30 04:12 UTC
