### ISSUE TITLE
the program cannot be used normally. Too many p2p ports are occupied

### ISSUE THREAD

**Issue by sundafa** [bnb-chain/bsc#1288] opened 2023-01-31 07:36 UTC
#### System information

Geth version: 1.1.18  
OS & Version: Linux
Commit hash : cb9e50bdf62c6b46a71724066d39f9851181a5af

#### Expected behaviour
Provide rpc service normally

#### Actual behaviour
It is normally used as an rpc node, but after a long time, the node cannot be used, and the number of p2p port connection clo states is too large
log
```
Jan 31 07:28:32 node-Singapore-ovh-5 geth_bsc[3737107]: 2023/01/31 07:28:32 http: Accept error: accept tcp [::]:31041: accept4: too many open files; retrying in 1s
Jan 31 07:28:33 node-Singapore-ovh-5 geth_bsc[3737107]: 2023/01/31 07:28:33 http: Accept error: accept tcp [::]:31041: accept4: too many open files; retrying in 1s
Jan 31 07:28:34 node-Singapore-ovh-5 geth_bsc[3737107]: 2023/01/31 07:28:34 http: Accept error: accept tcp [::]:31041: accept4: too many open files; retrying in 1s
Jan 31 07:28:35 node-Singapore-ovh-5 geth_bsc[3737107]: ERROR[01-31|07:28:35.507] Empty cpu stats
```

![image](https://user-images.githubusercontent.com/24621599/215695186-a26f2817-ba9c-45f6-b4a8-1d2c0066db06.png)

The p2p port is heavily occupied and is in the clo state until the program cannot be used normally
![image](https://user-images.githubusercontent.com/24621599/215695407-ecf0619d-7b05-4177-b437-308aa805687c.png)

#### Steps to reproduce the behaviour
The config.toml file uses the official configuration
run cmd: `/usr/local/bin/geth_bsc --networkid 56 --config /node/full/bsc/config.toml --datadir /node/full/bsc/ --syncmode full --gcmode full --diffsync --txlookuplimit=0 --tries-verify-mode=none --pruneancient=true --diffblock=5000 --http.vhosts=* --http.corsdomain=* --http --http.api=eth,web3,net,debug,txpool --http.addr 0.0.0.0 --ws --ws.api=eth,web3,net,debug,txpool --ws.addr 0.0.0.0 --metrics --metrics.addr 0.0.0.0 --port 31040 --http.port 31041 --ws.port 31042 --metrics.port 31045`

#### Backtrace

````
````

When submitting logs: please submit them as text and not screenshots.

**Comment by sundafa** [comment] 2023-02-01 03:12
Could it be caused by this parameter in the default configuration file?
```
[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
```

**Comment by qwzhou89** [comment] 2023-08-07 03:25
Our node generated the same error and then the node blocks stopped synchronizing. It lasted for over an hour before the node hung. After a reboot the node returned to normal.
```
t=2023-08-06T03:59:32+0800 lvl=eror msg="Empty cpu stats"
t=2023-08-06T03:59:35+0800 lvl=eror msg="Empty cpu stats"
t=2023-08-06T03:59:38+0800 lvl=eror msg="Empty cpu stats"
t=2023-08-06T03:59:41+0800 lvl=eror msg="Empty cpu stats"
t=2023-08-06T03:59:44+0800 lvl=eror msg="Empty cpu stats"
t=2023-08-06T03:59:47+0800 lvl=eror msg="Empty cpu stats"
t=2023-08-06T03:59:50+0800 lvl=eror msg="Empty cpu stats"
``` 
It feels like the two parameters `--tries-verify-mode=none --pruneancient=true `might be the cause.

Next time when the error occurs, I will check the rpc service and p2p port connection status of the node.

**Comment by CocoStarZ** [comment] 2023-09-08 04:19
Please upgrade to the latest version and retry. close the issue for now

**Closed by CocoStarZ** 2023-09-08 04:19 UTC
