### ISSUE TITLE
########## BAD BLOCK #########  

### ISSUE THREAD

**Issue by xiejing-yinshan** [bnb-chain/bsc#2039] opened 2023-12-06 08:43 UTC
#### System information
ubuntu 22.04 

Geth version: `1.3.1`
OS & Version: Linux

with params : --http.api 'web3,eth,net,debug,personal' --history.transactions=0  --syncmode=full --pruneancient=true --tries-verify-mode=local --db.engine=pebble

the correct hash is 0x4d7d25e56729a42d482c30724ee0c09aa25b943c8fd0798d5357829c12778834,  but always  expect the wrong hash : 0xf7081432db786e6abb7c37bba6dbe41e849f777db20bcab4dbf0cdf298ec16e4

I replace with 1.3.4 and rollbacked 100 blocks, but the error still exists

here is the trace:

#### Backtrace

````
t=2023-12-06T08:37:09+0000 lvl=eror msg="\n########## BAD BLOCK #########\nBlock: 34046194 (0x0f683eb2cbbbb10295ae3a1f8876152e9bf9303b1131716c30f90d75c6597efe)\nError: expected tx hash 0xf7081432db786e6abb7c37bba6dbe41e849f777d
b20bcab4dbf0cdf298ec16e4, get 0x4d7d25e56729a42d482c30724ee0c09aa25b943c8fd0798d5357829c12778834, nonce 1442945, to 0x0000000000000000000000000000000000001002, value 2704755000870959, gas 9223372036854775807, gasPrice 0, data \
nPlatform: geth (devel) go1.20.11 amd64 linux\nVCS: 885de2c1-20231204 (dirty)\nChain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:
0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<
nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0,
 NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, PlanckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048
, HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x48c4f20), IsDevMode:false}\nReceipts: \n  0: cumulative: 21000 gas: 21000 contract: 0x00000000000
00000000000000000000000000000 status: 1 tx: 0x2a8c0709d809498faf7daa76a1f4e98cd09e47c72588ad5354231ecd3cbd29ee


t=2023-12-06T08:37:09+0000 lvl=warn msg="Synchronisation failed, dropping peer" peer=c750e82db14453589128e98216e91735e2d2689673e94b5cf8ed43187ad62c6c err="retrieved hash chain is invalid: expected tx hash 0xf7081432db786e6abb7c
37bba6dbe41e849f777db20bcab4dbf0cdf298ec16e4, get 0x4d7d25e56729a42d482c30724ee0c09aa25b943c8fd0798d5357829c12778834, nonce 1442945, to 0x0000000000000000000000000000000000001002, value 2704755000870959, gas 9223372036854775807
, gasPrice 0, data "
````

**Comment by deepcrazy** [comment] 2023-12-06 16:29
Are you trying to run bsc fast node? If so, Which snapshot you used?
Can you also share your full geth startup command?

Also, Do share more logs (around 40-50 lines). And What is the output of `net.peerCount`, `eth.syncing` and `eth.blockNumber` commands?

**Comment by CocoStarZ** [comment] 2023-12-07 01:29
For v1.3.x Nodes:

   - Upgrade to the latest version, Geth v1.3.4. The download link and installation instructions can be found [BSC geth v1.3.4](https://github.com/bnb-chain/bsc/releases/tag/v1.3.4?ref=bnbchain.ghost.io).

Attention:

Since v1.3.1, the flags --txlookuplimit has been replaced by --history.transactions. Make sure you no longer use --txlookuplimit, otherwise, node may not start.

Find more details here: https://www.bnbchain.org/en/blog/hotfix-hardfork-for-bsc-testnet-and-mainnet

**Comment by zzzckck** [comment] 2023-12-13 07:05
> #### System information
> ubuntu 22.04
> 
> Geth version: `1.3.1` OS & Version: Linux
> 
> with params : --http.api 'web3,eth,net,debug,personal' --history.transactions=0 --syncmode=full --pruneancient=true --tries-verify-mode=local --db.engine=pebble
> 
> the correct hash is 0x4d7d25e56729a42d482c30724ee0c09aa25b943c8fd0798d5357829c12778834, but always expect the wrong hash : 0xf7081432db786e6abb7c37bba6dbe41e849f777db20bcab4dbf0cdf298ec16e4
> 
> I replace with 1.3.4 and rollbacked 100 blocks, but the error still exists
> 
> here is the trace:
> 
> #### Backtrace
> ```
> t=2023-12-06T08:37:09+0000 lvl=eror msg="\n########## BAD BLOCK #########\nBlock: 34046194 (0x0f683eb2cbbbb10295ae3a1f8876152e9bf9303b1131716c30f90d75c6597efe)\nError: expected tx hash 0xf7081432db786e6abb7c37bba6dbe41e849f777d
> b20bcab4dbf0cdf298ec16e4, get 0x4d7d25e56729a42d482c30724ee0c09aa25b943c8fd0798d5357829c12778834, nonce 1442945, to 0x0000000000000000000000000000000000001002, value 2704755000870959, gas 9223372036854775807, gasPrice 0, data \
> nPlatform: geth (devel) go1.20.11 amd64 linux\nVCS: 885de2c1-20231204 (dirty)\nChain config: &params.ChainConfig{ChainID:56, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:
> 0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:31302048, YoloV3Block:<nil>, CatalystBlock:<nil>, LondonBlock:31302048, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<
> nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, RamanujanBlock:0,
>  NielsBlock:0, MirrorSyncBlock:5184000, BrunoBlock:13082000, EulerBlock:18907621, GibbsBlock:23846001, NanoBlock:21962149, MoranBlock:22107423, PlanckBlock:27281024, LubanBlock:29020050, PlatoBlock:30720096, HertzBlock:31302048
> , HertzfixBlock:34140700, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil), Parlia:(*params.ParliaConfig)(0x48c4f20), IsDevMode:false}\nReceipts: \n  0: cumulative: 21000 gas: 21000 contract: 0x00000000000
> 00000000000000000000000000000 status: 1 tx: 0x2a8c0709d809498faf7daa76a1f4e98cd09e47c72588ad5354231ecd3cbd29ee
> 
> 
> t=2023-12-06T08:37:09+0000 lvl=warn msg="Synchronisation failed, dropping peer" peer=c750e82db14453589128e98216e91735e2d2689673e94b5cf8ed43187ad62c6c err="retrieved hash chain is invalid: expected tx hash 0xf7081432db786e6abb7c
> 37bba6dbe41e849f777db20bcab4dbf0cdf298ec16e4, get 0x4d7d25e56729a42d482c30724ee0c09aa25b943c8fd0798d5357829c12778834, nonce 1442945, to 0x0000000000000000000000000000000000001002, value 2704755000870959, gas 9223372036854775807
> , gasPrice 0, data "
> ```

If you are running as fast node, with the snapshot provided by 48Club, then you need to add this flag: ` --tries-verify-mode=none`
refer: https://github.com/48Club/bsc-snapshots?tab=readme-ov-file#geth-fast-node

And fast node does not support long reorg, i.e. `rollbacked 100 blocks ` is not supported.

**Comment by bnb-alexlucaci** [comment] 2023-12-13 16:39
@xiejing-yinshan can you please tell us if you are running fast node with the snapshot provided by 48club? Thanks!

**Comment by buddh0** [comment] 2024-01-09 03:33
no more information provoided by user, so I close this issue for two reasons:
1) in recent one month, there are no `BAD BLOCK` reported
2) I can't reproduce this issue locally, using snapshot from club48

**Closed by buddh0** 2024-01-09 03:33 UTC
