### ISSUE TITLE
Slash when double signing not working at the moment in BSC

### ISSUE THREAD

**Issue by datacryp** [bnb-chain/bsc#1200] opened 2022-11-23 21:27 UTC
So I came across to this [issue](https://github.com/bnb-chain/bnc-cosmos-sdk/issues/306) in the [bnc-cosmos-sdk](https://github.com/bnb-chain/bnc-cosmos-sdk), and I decided to test it to see if I could perform the slash using the modification of that library compiling the bnbcli and the full node binaries.

With a set of evidences  (which I'm not going to share), the compiled binaries and a fully synced node, I tested if slashing was still possible. However, I did not manage to get a successful answer from the node. It always answers with the error `Timed out waiting for tx to be included in a block`.

The issue here, is that at the moment it is not possible to slash any validator which is actually double signing some of their blocks, which can directly affect the health and security of the bsc network.

**Comment by mikelgutizubi** [comment] 2022-11-23 21:53
Slashing for double signing is a must to ensure BSCs healthiness. That issue has been opened for four days and still doesn't look like they are trying to fix it. I think that developers should give an answer to this issue and fix it as soon as possible.

If it is true that some validators are having this behavior they must be **punished**. This makes me wonder if this mechanism has ever worked at all. As far as I am concerned, there is no double signing slash history, what makes me think that this has never worked at all.

Lets see if someone can explain what is going on.

**Comment by guagualvcha** [comment] 2022-11-24 09:49
1. We have reviewed the code after being alerted to a reported issue with a validator. It has been discovered that there is a chance that a validator can, theoretically and non-maliciously, double-sign a block. This can be caused by  WriteBlockAndSetHead failure or slow execution.
2. We are not sure which case the specific validator encountered, because of a lack of detailed logs.  We already added a watchdog to prevent any non-maliciously double sign, please check https://github.com/bnb-chain/bsc/pull/1201.  We will release it soon within one week.
3. The double sign slashing mechanism will return once the problematic double sign logic has been further reviewed and fixed. Please check PR: https://github.com/bnb-chain/bsc/pull/1201

**Comment by Ezkerrox** [comment] 2022-11-24 10:53
Hey, I did send the evidence to one of the validators team so they could check what was going on. However, we still have tens of evidences from 11 different validators that happened in the last 5 days. We saved full blocks, we can share them with the team if that might help to find the root of the problem.
Each evidence looks different so it might be worth it to check them.
My username at discord is Ezkerrox#8746 if you need anything.
@guagualvcha

**Comment by guagualvcha** [comment] 2022-11-24 13:01
> Hey, I did send the evidence to one of the validators team so they could check what was going on. However, we still have close to 50 evidences from 11 different validators that happened in the last 5 days. We saved full blocks, we can share them with the team if that might help to find the root of the problem.

reaching you.

**Comment by guagualvcha** [comment] 2022-11-24 13:16
The issue is possibly introduced by this PR: https://github.com/bnb-chain/bsc/pull/975/files

**Comment by Ezkerrox** [comment] 2022-11-24 14:02
> > Hey, I did send the evidence to one of the validators team so they could check what was going on. However, we still have close to 50 evidences from 11 different validators that happened in the last 5 days. We saved full blocks, we can share them with the team if that might help to find the root of the problem.
> 
> reaching you.

Didn’t get any request.

**Comment by guagualvcha** [comment] 2022-11-24 14:05
> Didn’t get any request.

The developer is on the way home...

**Comment by Ezkerrox** [comment] 2022-11-24 15:05
> > Didn’t get any request.
> 
> The developer is on the way home...
Oh okey I will wait


> The issue is possibly introduced by this PR: https://github.com/bnb-chain/bsc/pull/975/files which tries to broadcast the block before it is persisted. The `writeBlockWithState` could take a lot of time because it may need to flush the MPT cache into the database, sometime it makes take more than 10 seconds, and then the `recommit` logic is trigger in the `worker.go`

In some of the evidence we found, some validators were broadcasting double signed blocks 25 second late compared to the header time. We can also add in the evidence the time difference between the header time and the time at those blocks were seen in the network.

**Comment by brilliant-lx** [comment] 2022-11-24 15:18
> > > Didn’t get any request.
> > 
> > 
> > The developer is on the way home...
> 
> Oh okey I will wait
> 
> > The issue is possibly introduced by this PR: https://github.com/bnb-chain/bsc/pull/975/files which tries to broadcast the block before it is persisted. The `writeBlockWithState` could take a lot of time because it may need to flush the MPT cache into the database, sometime it makes take more than 10 seconds, and then the `recommit` logic is trigger in the `worker.go`
> 
> In some of the evidence we found, some validators were broadcasting double signed blocks 25 second late compared to the header time. We can also add in the evidence the time difference between the header time and the time at those blocks were seen in the network.

Hi Ezkerrox, are you there? just reached you in discord

**Comment by Ezkerrox** [comment] 2022-11-24 23:57
Here is a small review of what we found, in case is useful to find the root problem / problems, we also introduce the new term of triple signing.

We have been gathering blocks for the last 5 days and we concluded that 13 different validators have produced double signed (even triple signed) blocks, with a total of 44 double sign evidence.

The table found below, shows a summary of some of the evidence we have found. For every block number, tables shows how many txs were included in the block, difficulty of the block (1 -> out of  turn block production,2->in turn block production), block header time, time difference, which defines the difference in seconds between the header time and the time in which the block has been seen in the network (broadcasted by the validator), validator and block hash. Block parent has been omitted because it doesn’t give any information (all blocks from same height in the table have same parent).

From the table we can summarize the next results:
* *Number of txs*: it is relevant to note that in some cases, blocks are proposed with no transaction. Is this a normal behavior? Even out of turn blocks that should have slashing tx inside them are proposed with no tx inside. 
* *Header time*: we find three different cases here:
  * Time of proposed headers are the same: Some examples of this are 23180509 and 23297847. In these cases, both blocks are committed and broadcasted at almost the same time. We can check how both headers have the same time and are broadcasted at almost the same exact time (time difference is between 10-200ms).
If we go deeper in these cases, the block that got broadcasted first (even if their broadcast time differs in tens of ms) was the one selected as parent of the next block. What is a bit worrying is that in some cases the 0 tx block was broadcasted some ms before the other block which had some transactions in it. The result of this is a delay on transaction execution (if block includes 0 tx, some tx might get executed 3 seconds late (next block)), no miner reward / no slash (if the block was off turn). In fact, 23280572 and 23303893 were off-turn blocks that were mined with 0 tx in it -> no slash was made.
  * Time of proposed headers differ by a couple of seconds: Some examples of this are 23249507 and 23282705. In these cases, there is a difference of 3-4 seconds between the first and second header time. Is important to note how these headers are being broadcasted slowly (time difference is between 1-4 seconds).
  * Time of proposed headers differs by tens of seconds. Some examples of this are 23280568 and 23331061. In both cases, each validator triple signed blocks. We can see how for the first and second header the time difference is 1-3 seconds, which is like the case before. However, the third header is committed 10 seconds after the second header in both cases (This delay of 10 seconds seems to appear in more cases such as 23307211, 23279533). Note that the time needed to broadcast the blocks increases from 1 second to 23 seconds in the most extreme case.
* *Miner*: it does not look like it is something miner related; it looks more of a bug in BSC client. However, it is important to note that validator ANKR is the one having the worst behavior, out of 44 evidences 28 were from ANKR validator.



---


## Summary Table
| BlockNumber | Txs | Difficulty | Header Time | Time difference (s) | Miner      | Block hash                                                         |
|-------------|-----|------------|-------------|---------------------|------------|--------------------------------------------------------------------|
| 23192368    | 111 | 1          | 15:32:24    | 1.038157008         | Ankr       | 0xec7e510d982213df7a5bd55e47e5ec1d56936e7023910f55c1d7611fe213dfe8 |
| 23192368    | 1   | 1          | 15:32:29    | 3.024972071         | Ankr       | 0x298140f9e2436ea64f189012b1cbcc8c166370e4181d0a565dfb637c873ef30d |
| 23249507    | 22  | 1          | 15:44:09    | 1.0101704           | Ankr       | 0x9890b3ac6c31df9e2261995f3fc976289a216b3baa1ea8a22bfb6c71c89906c3 |
| 23249507    | 1   | 1          | 15:44:14    | 1.266837497         | Ankr       | 0x071cf06a43ef50c6b0516b93bf488dee165c9195e15277a4d2e4e35cc8e05675 |
| 23282705    | 63  | 1          | 19:52:37    | 1.010432583         | Ankr       | 0xa0070f31cea44346faebd236c90ab0ff79ba04ac45bf4d8cd59dff9895e5ea17 |
| 23282705    | 0   | 1          | 19:52:40    | 4.167217972         | Ankr       | 0xe94e30dc24304f6a2288f2556c991df300d33884b239663656eaca998cf8b097 |
| 23297847    | 273 | 1          | 08:40:54    | 0.012896408         | Legend III | 0x039ad90d408c57bc38eb0fac64c3ead45908783faffbee8d6f2bdb92f07e9372 |
| 23297847    | 5   | 1          | 08:40:54    | 0.065722752         | Legend III | 0x380c9c57ef3c5746c6a324f04e729cdcf4c99fe9f790d91f59bdf9f3993936b0 |
| 23303893    | 0   | 1          | 13:47:09    | 0.005338049         | Legend II  | 0xd1de2c11ea04d386407bdd27857dc9018eaeb54d8e2de7b34673257b8376ce97 |
| 23303893    | 355 | 1          | 13:47:09    | 0.206800889         | Legend II  | 0xf7cb79edcc011f1b3fbdc7fd99420484a2bc45ad675d406e1680f9d17b35740c |
| 23302560    | 0   | 1          | 12:39:34    | 1.007451919         | Ankr       | 0xa242f33b153883c9a6a3c3eeba54f022010b50a5dde33c22ad4ed3f69fbce16c |
| 23302560    | 274 | 1          | 12:39:34    | 10.6327887          | Ankr       | 0x0014aaabb10724ca6b09b342bcaaebacd9c901aa0124967c4716f5f64a6fffa8 |
| 23280572    | 0   | 2          | 18:01:47    | 0.012381998         | Certik     | 0x386d01bf8aafb228c475c3d1da8d5fa52b84e820102fa2e4e212bed61190d3fd |
| 23280572    | 137 | 2          | 18:01:47    | 0.172658147         | Certik     | 0x02e856e41a3f668aacc5645b5dd90ee8d9d39f7062d5efcbd3972f4d7db8012c |
| 23180509    | 109 | 1          | 05:31:45    | 0.015383533         | TW Staking | 0xae1f6dccb9c5f758c63cc62bd0734c10e00ee09ebdd3bd49dcfc7a32062c79ac |
| 23180509    | 0   | 1          | 05:31:45    | 0.027842483         | TW Staking | 0xc0587fb9c922740850d4f7234c551c6d7d315bb85fa6bcba2f6585ca81e174f3 |
| 23331042    | 106 | 1          | 12:40:07    | 1.202713279         | BitStack   | 0x48a398d26c978f556eedab432c1412fe2b1188073956672a6ee76c9b5a8e8f09 |
| 23331042    | 526 | 1          | 12:40:07    | 25.39225980         | BitStack   | 0x78201621d75b96672a0d59f0b73e2cfa06d99c3f9711f142544f4d1c7314dfc5 |
| 23331042    | 1   | 1          | 12:40:24    | 8.657355158         | BitStack   | 0x7897b91edb61ffee4549693cb191479ce150f3ba01c86f2e0de54b52949f455e |
| 23303893    | 0   | 2          | 13:47:09    | 0.005338049         | Legend II  | 0xd1de2c11ea04d386407bdd27857dc9018eaeb54d8e2de7b34673257b8376ce97 |
| 23303893    | 355 | 2          | 13:47:09    | 0.206800889         | Legend II  | 0xf7cb79edcc011f1b3fbdc7fd99420484a2bc45ad675d406e1680f9d17b35740c |
| 23182983    | 22  | 1          | 07:37:58    | 4.777209464         | Figment    | 0x84542f73f8ec3c7cd6bca309cc03ef987ff413fee9b0716e227e378c748cd1e6 |
| 23182983    | 3   | 1          | 07:38:01    | 1.80851174          | Figment    | 0x3491c6bfe4c8f90e6d84df6dbd2364c8ef32086c2a4bdb5c446df276f947309f |
| 23307211    | 1   | 1          | 16:34:09    | 1.093869913         | Syn        | 0x667a04d59fb1620686bd3ffb121f20a11a84ba132818a6fd56d04e42183b784a |
| 23307211    | 1   | 1          | 16:34:19    | 18.255586836        | Syn        | 0x56da34127d794d9b644c787270d9b905be78d880b2e4c74e51dd9593da3f2181 |
| 23307211    | 1   | 1          | 16:34:29    | 8.32905778s         | Syn        | 0xebbbf479a26ea454a603ea037e9ca927102dc79505ae5e22925b96b97471bc7e |
| 23279533    | 927 | 1          | 17:08:26    | 1.065598574         | NodeReal   | 0xfd75c4791424c273bb18ac9bce4cc9081da51f08a3acd36309c234cd09435e36 |
| 23279533    | 1   | 1          | 17:08:31    | 21.502193501        | NodeReal   | 0x830aa1b0ecfdafd7825060440eeb20eef4e56c74b7473161817af6984af6cd6b |
| 23279533    | 1   | 1          | 17:08:41    | 11.788767596        | NodeReal   | 0x7a465c0fbce28a06d803c4eb9ec07d73fe99c50e9439f3631165f1f6b34d4526 |
| 23280568    | 3   | 1          | 18:01:37    | 0.669635362         | HashQuark  | 0x7b42ba9c014b2ca8371eaad02cb45630cf9dbf4f1ad3cd4cd64a639374766107 |
| 23280568    | 6   | 1          | 18:01:38    | 14.407134279        | HashQuark  | 0x7ddf36b98fa9f1074db24bb88b2a1d312fa6c6700f0e03f2925aa54d12183aad |
| 23280568    | 1   | 1          | 18:01:48    | 23.712257755        | HashQuark  | 0xc230fc5afc5e34231e61c0631ba72cd3ca11470e988564f10524253ebff83641 |
| 23331061    | 724 | 1          | 12:41:17    | 1.034010674         | MathWallet | 0x31cdb0b21b0b33755873b1df3fe5bdc880b7df07159e4cb8a8cddb6a8ae14be3 |
| 23331061    | 1   | 1          | 12:41:20    | 16.305817196s       | MathWallet | 0xc57ccae4ccf95185c50fb42b9fc3001c9913f2ffe529d16df8e407c58197d7ea |
| 23331061    | 1   | 1          | 12:41:30    | 7.025060209s        | MathWallet | 0x1462b8ca1dcb4c1451fb446663510f3b7eacf2cc86e3de1e70ab1820c6dd6b97 |



---

As a general comment we can state that this issue seems geth client related. That some of the cases with large header time differences between the double signed blocks and large block broadcast times, seem to be related with the validators having some high workload being done at the same time of the block proposals. They seem to be having problems importing new blocks so they keep trying to propose new blocks with the same height. On the other side, we have the case where a validator proposes and broadcasts two new blocks almost at the same time, with no delay, being one of them full of txs and the other one with 0, or close to 0 txs ,which doesn’t look to be related to any workload problem.

**Closed** 2023-09-08 04:28 UTC
