### ISSUE TITLE
Node imported blocks in batch rather than 1 block every 3 seconds after stopping for somewhile

### ISSUE THREAD

**Issue by isaacyuno** [bnb-chain/bsc#1436] opened 2023-04-11 07:16 UTC
#### System information

Geth version: 1.1.22
OS & Version: Linux
Peers are using the latest config.toml and appended those from [https://api.binance.org/v1/discovery/peers](https://api.binance.org/v1/discovery/peers%EF%BC%8C%E7%BB%8F%E5%B8%B8msg=)

#### Expected behaviour
Import 1 block every 3 seconds, having logs like below

t=2023-04-10T23:59:36+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=127  mgas=19.365  elapsed=708.409ms   mgasps=27.335   number=27,239,998 hash=0x4b0f5494472a3c957a3633197cb78e96aa7f7de3fe4179d1c95283ccc5049d8c dirty="211.56 MiB"
t=2023-04-10T23:59:40+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=38   mgas=3.288   elapsed=57.243ms    mgasps=57.436   number=27,239,999 hash=0xd840cd8d9249395bd68feda60a3b42802e2e5f47a8aa0aa845254539886f12fd dirty="211.29 MiB"

#### Actual behavior
Import ~20 blocks every time then deep frozen.

t=2023-04-11T06:42:35+0000 lvl=info msg="Imported new chain segment"             blocks=21  txs=3147 mgas=357.867 elapsed=6.356s      mgasps=56.301 number=27,247,997 hash=0x0b3aceb24dd0841fcba033e7c6eb82594a50f7d3dd802995c140033627c3887d dirty="403.71 MiB" ignored=1
t=2023-04-11T06:43:24+0000 lvl=info msg="Deep froze chain segment"               blocks=21  elapsed=19.568ms    number=27,157,997 hash=0xff53a1040cad414710461942d6c62001749d56c9d1e206c0638f5ba240034be8
t=2023-04-11T06:43:35+0000 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=0   itemSize="47.65 KiB" throttle=5502
t=2023-04-11T06:43:43+0000 lvl=info msg="Imported new chain segment"             blocks=16  txs=2540 mgas=274.542 elapsed=8.257s      mgasps=33.248 number=27,248,013 hash=0x10b8bb32979437cfa82d5c36e7694f319198391e4d671279b2b9a127b025f6d8 dirty="416.72 MiB" ignored=1
t=2023-04-11T06:43:46+0000 lvl=info msg="Imported new chain segment"             blocks=5   txs=704  mgas=111.286 elapsed=3.113s      mgasps=35.741 number=27,248,018 hash=0x4cce094577a8043cf35ef863037e6badaa3243f4ccab55d9d444a23dbe6bbe03 dirty="422.10 MiB"
t=2023-04-11T06:44:24+0000 lvl=info msg="Deep froze chain segment"               blocks=21  elapsed=20.075ms    number=27,158,018 hash=0xb05894d1683ed12f2c91d00b6e72f4849e701c0caf99bf29e0fa757642fdbdde
t=2023-04-11T06:44:40+0000 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=0   itemSize="45.29 KiB" throttle=5789
t=2023-04-11T06:44:49+0000 lvl=info msg="Imported new chain segment"             blocks=20  txs=2898 mgas=367.159 elapsed=9.103s      mgasps=40.330 number=27,248,038 hash=0xbd14e7fca5f08f28b145f52453a20c42e0ee00305b1ef597b807d2415e8ccc54 dirty="438.98 MiB"
t=2023-04-11T06:45:24+0000 lvl=info msg="Deep froze chain segment"               blocks=20  elapsed=21.186ms    number=27,158,038 hash=0x6f531fbd08f51065906cc7fb4c038fc4a1cd164e3c4e8bd7c3607fb718cab53b
t=2023-04-11T06:45:46+0000 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=0   itemSize="43.45 KiB" throttle=6034

#### Steps to reproduce the behaviour
Using the official snapshot with below start-up command, it's a full node, not a fast node.
./geth --config ./config.toml --datadir ./node --cache 12000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --http.addr 0.0.0.0 --http.port 8091 --http.api eth,net,web3,txpool,admin,debug --ws --ws.addr 0.0.0.0 --ws.port 443 --ws.api eth,net,web3,txpool,admin,debug

If I stop the node for like more than 30 minutes, then restart it, it will always run into this symptom.

#### Backtrace
Attached bsc.log, set level to trace.
[Archive.zip](https://github.com/bnb-chain/bsc/files/11197576/Archive.zip)

I tested 1.1.19 (stopped 30 minutes then restart) and it imported blocks initially but hang at below logs
t=2023-04-11T08:30:46+0000 lvl=info msg="Deep froze chain segment"               blocks=28  elapsed=22.414ms  number=27,160,107 hash=0xe63beee8bacca8cf88da8aa425c09055c1d881b1a503bc179fab5c5132a779a1
Attached trace level log
[bsc 1.1.19.log](https://github.com/bnb-chain/bsc/files/11198513/bsc.1.1.19.log)

tested 1.1.22 with a fast node, there is no issue
Attached trace level log
[fastnode.log](https://github.com/bnb-chain/bsc/files/11198517/fastnode.log)

**Comment by lk479o000** [comment] 2023-04-11 11:53
After upgrading to 1.1.21 or 1.1.22, the same goes for me.
t=2023-04-11T11:28:30+0000 lvl=info msg="Deep froze chain segment"

**Comment by 0xbundler** [comment] 2023-04-12 06:12
Thanks for your report, the issue is a stubborn problem, you may try using the recommended config from the [release v1.1.22](https://github.com/bnb-chain/bsc/releases/tag/v1.1.22), and clean local peers.

here are some other related issues: https://github.com/bnb-chain/bsc/issues/1437, https://github.com/bnb-chain/bsc/issues/1106

**Comment by gituser** [comment] 2023-04-12 21:30
> @0xbundler What config are you referring to? As far as I know there were no changes in config from previous versions. How to clean local peers and what are "local" peers?
> 
> I have two identical nodes, and one is perfectly fine, and behaviour of the second one is nondeterministic, it gets stuck in "Deep froze chain segment" randomly, and sometimes it manages to get out by itself.

Try doing this:
* download latest mainnet config https://github.com/bnb-chain/bsc/releases/download/v1.1.22/mainnet.zip and extract `StaticPeers` and `BootNodes` and replace those in your old config or replace whole config altogether
* stop bsc with e.g. `systemctl stop bsc` or whatever script you're using
* remove inside the datadir folder `geth/nodes`
* start bsc again with `systemctl start bsc` it should be working correctly

**Comment by 0xbundler** [comment] 2023-04-13 03:28
> @0xbundler What config are you referring to? As far as I know there were no changes in config from previous versions. How to clean local peers and what are "local" peers?
> 
> I have two identical nodes, and one is perfectly fine, and behaviour of the second one is nondeterministic, it gets stuck in "Deep froze chain segment" randomly, and sometimes it manages to get out by itself.

After replacing StaticNodes, the problem is disappeared

First time, StaticNodes were taken from https://api.binance.org/v1/discovery/peers, may replace before.
Second time I filled StaticNodes from another working machine and problem is disappeared.

**Comment by brilliant-lx** [comment] 2023-04-14 07:04
Seems the connection is much better now, the issue could be caused by unstable P2P connections.
Close the issue right now, we will work on how to optimize the P2P network.

**Closed by brilliant-lx** 2023-04-14 07:04 UTC
Labels: bug
