### ISSUE TITLE
Transactions with 0 gwei are back²

### ISSUE THREAD

**Issue by wellgamer789** [bnb-chain/bsc#2371] opened 2024-04-05 12:38 UTC
https://github.com/bnb-chain/bsc/issues/658
https://github.com/bnb-chain/bsc/issues/1746

https://bscscan.com/txs?block=37593952
![image](https://github.com/bnb-chain/bsc/assets/29676107/11cbe41b-0edc-4f17-84b4-64f799854389)

This contract has been interacted with for over 8 hours with only 0 gwei transactions..
https://bscscan.com/address/0x3aac3e2731421551c675c973080921f97d2489da
![image](https://github.com/bnb-chain/bsc/assets/29676107/86b955cd-a8e6-4590-b36c-2abb256fd9a4)
![image](https://github.com/bnb-chain/bsc/assets/29676107/b3b8d5f6-394d-48f2-b6ad-9abd2a0f2766)

**Comment by wellgamer789** [comment] 2024-04-06 01:28
This has been happening for 24 hours, just this contract that I mentioned has already had interaction in 100K transactions with gwei 0, not to mention other bots.

**Comment by zzzckck** [comment] 2024-04-07 03:36
> This has been happening for 24 hours, just this contract that I mentioned has already had interaction in 100K transactions with gwei 0, not to mention other bots.

@wellgamer789 thank you for information, but they are probably the MEV bundle transactions. There are several MEV discussions on forum since last year: https://forum.bnbchain.org/search?q=mev
And there is also an official BEP: https://github.com/bnb-chain/BEPs/pull/322.
There is no consensus rule to exclude zero gas price right now, so far it is as expected, there is not much we can do.

**Comment by wellgamer789** [comment] 2024-04-07 14:23
They are not bundle transactions, just check the transactions and blocks, they created a lot of contracts and tokens using 0 gwei, for example several bots "minting XEN token". It's impressive that this chain supports massive spam of these things at no cost.
![image](https://github.com/bnb-chain/bsc/assets/29676107/4c105474-ed50-452a-aa08-eb6e54848d16)

**Comment by wellgamer789** [comment] 2024-04-07 14:24
Even scammers are taking advantage of this:
![image](https://github.com/bnb-chain/bsc/assets/29676107/4e7e2ffe-6bab-448d-94e2-64db1c53936e)

**Comment by zzzckck** [comment] 2024-04-08 02:11
> They are not bundle transactions, just check the transactions and blocks, they created a lot of contracts and tokens using 0 gwei, for example several bots "minting XEN token". It's impressive that this chain supports massive spam of these things at no cost. ![image](https://private-user-images.githubusercontent.com/29676107/320288408-4c105474-ed50-452a-aa08-eb6e54848d16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDE1NjgsIm5iZiI6MTcxMjU0MTI2OCwicGF0aCI6Ii8yOTY3NjEwNy8zMjAyODg0MDgtNGMxMDU0NzQtZWQ1MC00NTJhLWFhMDgtZWI2ZTU0ODQ4ZDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAxNTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NjdlYjU0MmExNjIyNWUyM2FlZDg5ZjU1ZTFiMTE3ZTJiNDhlNDhlNGMwNTUwYTZlMDFhYzBiMDFiNjViYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pks0i-3O2My3VanJ5WMAxuBaiMgGWagAHpzgGMZhfSA)

noted, thank you for feedback, it is not good for the chain, will check.

**Comment by AlexKNM** [comment] 2024-04-13 16:52
These transactions became a norm at 48 Club , Avengers, ..
https://bscscan.com/txs?block=37828567
https://bscscan.com/txs?block=37829010
and many other validators.

Is this a new norm where builders are allowed to add 0 cost transactions? or this is temporary bug?

**Comment by zzzckck** [comment] 2024-04-16 10:09
> These transactions became a norm at 48 Club , Avengers, .. https://bscscan.com/txs?block=37828567 https://bscscan.com/txs?block=37829010 and many other validators.
> 
> Is this a new norm where builders are allowed to add 0 cost transactions? or this is temporary bug?

It is not a bug, some validators choose to accept zero gas price to promote their own project...
I think, we need to figure out a GasPrice rule, implementation is easy, but need to reach consensus across the community first.

**Comment by wellgamer789** [comment] 2024-04-16 13:45
> Even scammers are taking advantage of this: ![image](https://private-user-images.githubusercontent.com/29676107/320288511-4e7e2ffe-6bab-448d-94e2-64db1c53936e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzUzMDcsIm5iZiI6MTcxMzI3NTAwNywicGF0aCI6Ii8yOTY3NjEwNy8zMjAyODg1MTEtNGU3ZTJmZmUtNmJhYi00NDhkLTk0ZTItNjRkYjFjNTM5MzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDEzNDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OGQ5OTM2MjMwMzg3ZmU1ZGNkODE2MjU1YTk4NjdjNTI0Y2VjYzQxMTg4OTlhYmY4MDVlYmQwM2M2ZWM5MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7zZ-aCWrL7lEm5nlE7h88_gqLJxfDR4tdO3tlirE3eY)

:/

**Comment by kaber2** [comment] 2024-04-21 21:34
> > These transactions became a norm at 48 Club , Avengers, .. https://bscscan.com/txs?block=37828567 https://bscscan.com/txs?block=37829010 and many other validators.
> > Is this a new norm where builders are allowed to add 0 cost transactions? or this is temporary bug?
> 
> It is not a bug, some validators choose to accept zero gas price to promote their own project... I think, we need to figure out a GasPrice rule, implementation is easy, but need to reach consensus across the community first.

I believe there is actually broad consensus within the community that while it seems unavoidable that miners are offering MEV services, they shouldn't be lining their pockets by abusing there position.

So how about someone actually asks the community for their opinion and brings up a vote? It is trivial to enforce transaction ordering rules and minimum gas prices on the consensus level for everyone.

**Comment by zzzckck** [comment] 2024-04-25 08:54
close it right now, need to reach agreement across the community first, but not easy.

**Closed by zzzckck** 2024-04-25 08:54 UTC

**Comment by kaber2** [comment] 2024-04-27 13:59
As I said, the first step would be to actually ask the community instead of stating again and again that we need community consensus and then doing nothing to reach it.

Please reopen.
